service: aws-postgres-serverless

frameworkVersion: '2'

provider:
  name: aws
  stage: production
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  timeout: 30

functions:

  getStates:
    handler: handler.getStates
    events:
      - http:
          method: get
          path: /getStates

  getGeoJsonForCsv:
    handler: handler.getGeoJsonForCsv
    events:
      - http:
          method: post
          path: /getGeoJsonForCsv

plugins:
  - serverless-offline