service: aws-postgres-serverless

frameworkVersion: '2'

provider:
  name: aws
  stage: production
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

functions:

  getDistrictsForState:
    handler: handler.getDistrictsForState
    events:
      - http:
          method: get
          path: /districtsForState/{state_abbrev}

  getGeoJsonForCsv:
    handler: handler.getGeoJsonForCsv
    events:
      - http:
          method: post
          path: /getGeoJsonForCsv

plugins:
  - serverless-offline