service: aws-postgres-serverless

frameworkVersion: '2'

provider:
  name: aws
  stage: production
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  timeout: 30

functions:

  states:
    handler: handler.getStates
    events:
      - http:
          method: get
          path: /states

  getStateForStusps:
    handler: handler.getStateForStusps
    events:
      - http:
          method: get
          path: /states/{stusps}
  
  getCountiesForStusps:
    handler: handler.getCountiesForStusps
    events:
      - http:
          method: get
          path: /counties/{stusps}

  geoJsonForCsv:
    handler: handler.getGeoJsonForCsv
    events:
      - http:
          method: post
          path: /getGeoJsonForCsv

plugins:
  - serverless-offline