exports.states = [
  {name: "Alabama", stusps: "AL", statefp: "01"},
  {name: "Alaska", stusps: "AK", statefp: "02"},
  {name: "Arizona", stusps: "AZ", statefp: "04"},
  {name: "Arkansas", stusps: "AR", statefp: "05"},
  {name: "California", stusps: "CA", statefp: "06"},
  {name: "Colorado", stusps: "CO", statefp: "08"},
  {name: "Connecticut", stusps: "CT", statefp: "09"},
  {name: "Delaware", stusps: "DE", statefp: "10"},
  {name: "District of Columbia", stusps: "DC", statefp: "11"},
  {name: "Florida", stusps: "FL", statefp: "12"},
  {name: "Georgia", stusps: "GA", statefp: "13"},
  {name: "Hawaii", stusps: "HI", statefp: "15"},
  {name: "Idaho", stusps: "ID", statefp: "16"},
  {name: "Illinois", stusps: "IL", statefp: "17"},
  {name: "Indiana", stusps: "IN", statefp: "18"},
  {name: "Iowa", stusps: "IA", statefp: "19"},
  {name: "Kansas", stusps: "KS", statefp: "20"},
  {name: "Kentucky", stusps: "KY", statefp: "21"},
  {name: "Louisiana", stusps: "LA", statefp: "22"},
  {name: "Maine", stusps: "ME", statefp: "23"},
  {name: "Maryland", stusps: "MD", statefp: "24"},
  {name: "Massachusetts", stusps: "MA", statefp: "25"},
  {name: "Michigan", stusps: "MI", statefp: "26"},
  {name: "Minnesota", stusps: "MN", statefp: "27"},
  {name: "Mississippi", stusps: "MS", statefp: "28"},
  {name: "Missouri", stusps: "MO", statefp: "29"},
  {name: "Montana", stusps: "MT", statefp: "30"},
  {name: "Nebraska", stusps: "NE", statefp: "31"},
  {name: "Nevada", stusps: "NV", statefp: "32"},
  {name: "New Hampshire", stusps: "NH", statefp: "33"},
  {name: "New Jersey", stusps: "NJ", statefp: "34"},
  {name: "New Mexico", stusps: "NM", statefp: "35"},
  {name: "New York", stusps: "NY", statefp: "36"},
  {name: "North Carolina", stusps: "NC", statefp: "37"},
  {name: "North Dakota", stusps: "ND", statefp: "38"},
  {name: "Ohio", stusps: "OH", statefp: "39"},
  {name: "Oklahoma", stusps: "OK", statefp: "40"},
  {name: "Oregon", stusps: "OR", statefp: "41"},
  {name: "Pennsylvania", stusps: "PA", statefp: "42"},
  {name: "Rhode Island", stusps: "RI", statefp: "44"},
  {name: "South Carolina", stusps: "SC", statefp: "45"},
  {name: "South Dakota", stusps: "SD", statefp: "46"},
  {name: "Tennessee", stusps: "TN", statefp: "47"},
  {name: "Texas", stusps: "TX", statefp: "48"},
  {name: "Utah", stusps: "UT", statefp: "49"},
  {name: "Vermont", stusps: "VT", statefp: "50"},
  {name: "Virginia", stusps: "VA", statefp: "51"},
  {name: "Washington", stusps: "WA", statefp: "53"},
  {name: "West Virginia", stusps: "WV", statefp: "54"},
  {name: "Wisconsin", stusps: "WI", statefp: "55"},
  {name: "Wyoming", stusps: "WY", statefp: "56"},
  {name: "Puerto Rico", stusps: "PR", statefp: "72"}
]
